server:
    port: 8094
spring:
  application:
    name: consumerService
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        prefix: application
        file-extension: yaml
  main:
    allow-bean-definition-overriding: true
exception:
  display:
    enable: true