server:
    port: 8093
spring:
  response:
    scan-package:
      - com.fushindcw
  application:
    name: providerService
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
      config:
        enabled: true
        server-addr: 127.0.0.1:8848
        prefix: application
        file-extension: yaml
  main:
    allow-bean-definition-overriding: true
springdoc:
  api-docs:
    enable: true
exception:
  display:
    enable: true